b = set()
print(type(b))
#adding value to an empty set
b.add(4)
b.add(5)
b.add(6)
b.add(6)
b.add(1)
b.add(7)
b.add(9)
# b.add([2,6,8])
# b.add({2,3,4})
print(b)
# print(len(b))
# b.remove(4)
# print(b)
# print(b.pop())
# print(b.clear)

#  print(b.union({4,8}))
# #    print(b)

# print(b.intersection({5}))
# #print(b)